export type DashboardColumn = { key: string; label: string };

export const MARKETING_COLUMNS: DashboardColumn[] = [
  { key: 'channel', label: 'Channel' },
  { key: 'budget', label: 'Budget' },
  { key: 'leads', label: 'Leads' },
  { key: 'cpl', label: 'CPL' },
  { key: 'no_answer_spam', label: 'No answer / Spam' },
  { key: 'rate_answer', label: '% rate answer' },
  { key: 'qualified_leads', label: 'Qualified Leads' },
  { key: 'cost_per_qualified_leads', label: 'Cost PerQualified Leads' },
  { key: 'cr_ql', label: 'CR QL' },
  { key: 'ql_actual', label: 'QL Actual' },
  { key: 'cpql_actual', label: 'CPQL_Actual' },
  { key: 'meetings', label: 'Meetings' },
  { key: 'cp_meetings', label: 'CP Meetings' },
  { key: 'deals', label: 'Deals' },
  { key: 'cost_per_deal', label: 'Cost Per Deal' },
  { key: 'revenue', label: 'Revenue' },
  { key: 'roi', label: 'ROI' },
  { key: 'company_revenue', label: 'Company revenue' },
];

export const RED_COLUMNS_MAIN: DashboardColumn[] = [
  { key: 'channel', label: 'Channel' },
  { key: 'budget', label: 'Budget' },
  { key: 'leads', label: 'Leads' },
  { key: 'cpl', label: 'CPL' },
  { key: 'no_answer_spam', label: 'No answer / Spam' },
  { key: 'rate_answer', label: '% rate answer' },
  { key: 'qualified_leads', label: 'Qualified Leads' },
  { key: 'cost_per_qualified_leads', label: 'Cost PerQualified Leads' },
  { key: 'ql_actual', label: 'QL Actual' },
  { key: 'cpql_actual', label: 'CPQL_Actual' },
  { key: 'meetings', label: 'Meetings' },
  { key: 'cp_meetings', label: 'CP Meetings' },
  { key: 'deals', label: 'Deals' },
  { key: 'cost_per_deal', label: 'Cost Per Deal' },
  { key: 'revenue', label: 'Revenue' },
  { key: 'roi', label: 'ROI' },
];

export const RED_COLUMNS_GEO: DashboardColumn[] = [
  { key: 'channel', label: 'Источник' },
  { key: 'leads', label: 'Leads' },
  { key: 'no_answer_spam', label: 'No answer / Spam' },
  { key: 'rate_answer', label: '% rate answer' },
  { key: 'qualified_leads', label: 'Qualified Leads' },
  { key: 'cr_ql', label: 'CR QL' },
  { key: 'ql_actual', label: 'QL Actual' },
  { key: 'meetings', label: 'Meetings' },
  { key: 'deals', label: 'Deals' },
  { key: 'revenue', label: 'Revenue' },
];

export const FACEBOOK_COLUMNS_MAIN: DashboardColumn[] = [
  { key: 'channel', label: 'Channel' },
  { key: 'leads', label: 'Leads' },
  { key: 'no_answer_spam', label: 'No answer / Spam' },
  { key: 'rate_answer', label: '% rate answer' },
  { key: 'qualified_leads', label: 'Qualified Leads' },
  { key: 'ql_actual', label: 'QL Actual' },
  { key: 'meetings', label: 'Meetings' },
  { key: 'deals', label: 'Deals' },
  { key: 'revenue', label: 'Revenue' },
];

export const WEBSITE_COLUMNS: DashboardColumn[] = [
  { key: 'channel', label: 'Группировка / UTM Source / Канал' },
  { key: 'impressions', label: 'Показы (Impressions)' },
  { key: 'clicks', label: 'Клики (Clicks)' },
  { key: 'ctr', label: 'CTR' },
  { key: 'ad_cost', label: 'Стоимость РК (Ad Cost)' },
  { key: 'sessions', label: 'Сессии (Sessions)' },
  { key: 'bounce_rate', label: 'Показатель отказов (Bounce Rate)' },
  { key: 'avg_duration', label: 'Средняя длительность сессии (Avg. Session Duration)' },
  { key: 'cr_lead', label: 'Конверсия в Лид (CR Lead)' },
  { key: 'leads_crm', label: 'Лиды CRM' },
  { key: 'leads_wa', label: 'Лиды с WhatsApp/Формы' },
  { key: 'no_answer_spam', label: 'No Answer / Spam' },
  { key: 'rate_answer', label: '% Rate Answer' },
  { key: 'qualified_leads', label: 'Квалифицированные Лиды (QL)' },
  { key: 'cr_ql_web', label: 'CR QL (QL/Лиды CRM)' },
  { key: 'meetings', label: 'Встречи (Meetings)' },
  { key: 'deals', label: 'Сделки (Deals)' },
  { key: 'cpql_web', label: 'Cost Per Qualified Lead (CPQL)' },
  { key: 'revenue', label: 'Revenue' },
  { key: 'roi', label: 'ROI' },
];